package com.xiaowu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBank<M extends BaseBank<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setBankCode(java.lang.String bankCode) {
		set("bank_code", bankCode);
	}

	public java.lang.String getBankCode() {
		return get("bank_code");
	}

	public void setBankName(java.lang.String bankName) {
		set("bank_name", bankName);
	}

	public java.lang.String getBankName() {
		return get("bank_name");
	}

	public void setPinYin(java.lang.String pinYin) {
		set("pin_yin", pinYin);
	}

	public java.lang.String getPinYin() {
		return get("pin_yin");
	}

}
