package com.xiaowu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCumulativeBookings<M extends BaseCumulativeBookings<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTeam(java.lang.String team) {
		set("team", team);
	}

	public java.lang.String getTeam() {
		return get("team");
	}

	public void setBank(java.lang.String bank) {
		set("bank", bank);
	}

	public java.lang.String getBank() {
		return get("bank");
	}

	public void setYqnymzh(java.math.BigDecimal yqnymzh) {
		set("yqnymzh", yqnymzh);
	}

	public java.math.BigDecimal getYqnymzh() {
		return get("yqnymzh");
	}

	public void setYqnjmslhjyth(java.math.BigDecimal yqnjmslhjyth) {
		set("yqnjmslhjyth", yqnjmslhjyth);
	}

	public java.math.BigDecimal getYqnjmslhjyth() {
		return get("yqnjmslhjyth");
	}

	public void setYmslwmdt(java.math.BigDecimal ymslwmdt) {
		set("ymslwmdt", ymslwmdt);
	}

	public java.math.BigDecimal getYmslwmdt() {
		return get("ymslwmdt");
	}

	public void setYmslxxz(java.math.BigDecimal ymslxxz) {
		set("ymslxxz", ymslxxz);
	}

	public java.math.BigDecimal getYmslxxz() {
		return get("ymslxxz");
	}

	public void setYmsldxz(java.math.BigDecimal ymsldxz) {
		set("ymsldxz", ymsldxz);
	}

	public java.math.BigDecimal getYmsldxz() {
		return get("ymsldxz");
	}

	public void setYqnjmsl(java.math.BigDecimal yqnjmsl) {
		set("yqnjmsl", yqnjmsl);
	}

	public java.math.BigDecimal getYqnjmsl() {
		return get("yqnjmsl");
	}

	public void setYjydjmsljyth(java.math.BigDecimal yjydjmsljyth) {
		set("yjydjmsljyth", yjydjmsljyth);
	}

	public java.math.BigDecimal getYjydjmsljyth() {
		return get("yjydjmsljyth");
	}

	public void setYlnjmsl(java.math.BigDecimal ylnjmsl) {
		set("ylnjmsl", ylnjmsl);
	}

	public java.math.BigDecimal getYlnjmsl() {
		return get("ylnjmsl");
	}

}
