package com.xiaowu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBottomSingle<M extends BaseBottomSingle<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setSerialNum(java.lang.String serialNum) {
		set("serial_num", serialNum);
	}

	public java.lang.String getSerialNum() {
		return get("serial_num");
	}

	public void setImgPath(java.lang.String imgPath) {
		set("img_path", imgPath);
	}

	public java.lang.String getImgPath() {
		return get("img_path");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
