package com.xiaowu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTeam<M extends BaseTeam<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}

	public java.lang.String getCode() {
		return get("code");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setLeader(java.lang.String leader) {
		set("leader", leader);
	}

	public java.lang.String getLeader() {
		return get("leader");
	}

	public void setLevel(java.lang.Integer level) {
		set("level", level);
	}

	public java.lang.Integer getLevel() {
		return get("level");
	}

	public void setParentCode(java.lang.String parentCode) {
		set("parent_code", parentCode);
	}

	public java.lang.String getParentCode() {
		return get("parent_code");
	}

	public void setIsDel(java.lang.Integer isDel) {
		set("is_del", isDel);
	}

	public java.lang.Integer getIsDel() {
		return get("is_del");
	}

}
