package com.xiaowu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysLog<M extends BaseSysLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setControllerName(java.lang.String controllerName) {
		set("controller_name", controllerName);
	}

	public java.lang.String getControllerName() {
		return get("controller_name");
	}

	public void setMethodName(java.lang.String methodName) {
		set("method_name", methodName);
	}

	public java.lang.String getMethodName() {
		return get("method_name");
	}

	public void setParameter(java.lang.String parameter) {
		set("parameter", parameter);
	}

	public java.lang.String getParameter() {
		return get("parameter");
	}

	public void setLoginUser(java.lang.String loginUser) {
		set("login_user", loginUser);
	}

	public java.lang.String getLoginUser() {
		return get("login_user");
	}

	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}

	public java.lang.String getIp() {
		return get("ip");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}

	public java.lang.String getCreateTime() {
		return get("create_time");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
