package com.xiaowu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFeedback<M extends BaseFeedback<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}

	public java.lang.String getCreateTime() {
		return get("create_time");
	}

	public void setOpenId(java.lang.String openId) {
		set("open_id", openId);
	}

	public java.lang.String getOpenId() {
		return get("open_id");
	}

	public void setSystemInfo(java.lang.String systemInfo) {
		set("system_info", systemInfo);
	}

	public java.lang.String getSystemInfo() {
		return get("system_info");
	}

	public void setUserNo(java.lang.String userNo) {
		set("user_no", userNo);
	}

	public java.lang.String getUserNo() {
		return get("user_no");
	}

	public void setWxUserInfo(java.lang.String wxUserInfo) {
		set("wx_user_info", wxUserInfo);
	}

	public java.lang.String getWxUserInfo() {
		return get("wx_user_info");
	}

	public void setPhoneWx(java.lang.String phoneWx) {
		set("phone_wx", phoneWx);
	}

	public java.lang.String getPhoneWx() {
		return get("phone_wx");
	}

	public void setProcessingState(java.lang.Integer processingState) {
		set("processing_state", processingState);
	}

	public java.lang.Integer getProcessingState() {
		return get("processing_state");
	}

}
