package com.xiaowu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseApiLog<M extends BaseApiLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}

	public java.lang.String getIp() {
		return get("ip");
	}

	public void setSysInfo(java.lang.String sysInfo) {
		set("sys_info", sysInfo);
	}

	public java.lang.String getSysInfo() {
		return get("sys_info");
	}

	public void setUserInfo(java.lang.String userInfo) {
		set("user_info", userInfo);
	}

	public java.lang.String getUserInfo() {
		return get("user_info");
	}

	public void setLogType(java.lang.Integer logType) {
		set("log_type", logType);
	}

	public java.lang.Integer getLogType() {
		return get("log_type");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}

	public java.lang.String getCreateTime() {
		return get("create_time");
	}

}
