package com.xiaowu.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("api_log", "id", ApiLog.class);
		arp.addMapping("bank", "id", Bank.class);
		arp.addMapping("bottom_single", "id", BottomSingle.class);
		arp.addMapping("cat_coin", "id", CatCoin.class);
		arp.addMapping("common_info", "id", CommonInfo.class);
		arp.addMapping("cumulative_bookings", "id", CumulativeBookings.class);
		arp.addMapping("dictionary", "id", Dictionary.class);
		arp.addMapping("feedback", "id", Feedback.class);
		arp.addMapping("product", "id", Product.class);
		arp.addMapping("sys_log", "id", SysLog.class);
		arp.addMapping("sys_user", "id", SysUser.class);
		arp.addMapping("t_user", "id", TUser.class);
		arp.addMapping("team", "id", Team.class);
		arp.addMapping("user_info", "id", UserInfo.class);
		arp.addMapping("version", "id", Version.class);
	}
}

