package com.xiaowu.common.model;

import com.xiaowu.common.model.base.BaseApiLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ApiLog extends BaseApiLog<ApiLog> {
	public static final ApiLog dao = new ApiLog().dao();
}
