package com.xiaowu.common.model;

import com.xiaowu.common.model.base.BaseBottomSingle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BottomSingle extends BaseBottomSingle<BottomSingle> {
	public static final BottomSingle dao = new BottomSingle().dao();
}
