package com.xiaowu.common.model;

import com.xiaowu.common.model.base.BaseCatCoin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CatCoin extends BaseCatCoin<CatCoin> {
	public static final CatCoin dao = new CatCoin().dao();
}
