package com.xiaowu.common.model;

import com.xiaowu.common.model.base.BaseCommonInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommonInfo extends BaseCommonInfo<CommonInfo> {
	public static final CommonInfo dao = new CommonInfo().dao();
}
