package com.xiaowu.common.model;

import com.xiaowu.common.model.base.BaseCumulativeBookings;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CumulativeBookings extends BaseCumulativeBookings<CumulativeBookings> {
	public static final CumulativeBookings dao = new CumulativeBookings().dao();
}
