package com.xiaowu.common.model;

import com.xiaowu.common.model.base.BaseFeedback;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Feedback extends BaseFeedback<Feedback> {
	public static final Feedback dao = new Feedback().dao();
}
